### ISSUE TITLE
Making tiny_yolov3 load

### ISSUE THREAD

**Issue by ordicker** [FluxML/ONNX.jl#83]
### Motivation and description

Hi, 

I was trying to contribute by making [tiny_yolo](https://github.com/onnx/models/raw/main/vision/object_detection_segmentation/tiny-yolov3/model/tiny-yolov3-11.onnx) load (followed the [resnet](https://github.com/FluxML/ONNX.jl/blob/3677b3f1ea0ddb1346a9797b1605d0b130236f38/examples/resnet18.jl) example). 
First question, is this project alive? I mean, I know it is under a big rewrite and the question is whether the community still needs this project? Is the rewrite failed in some way (Flux in compatibility)? etc... 

If it is alive, I have some question. 

1. the first thing I have stumbled upon was missing ONNX2JULIA_TYPES (mine was BOOL, and the error was a bit cryptic). 
I guess we should add all of those [types](https://github.com/onnx/onnx/blob/37ba77e1360d3691fede22d9dfe3f24e7fce8901/onnx/defs/parser.h#L74)  and have some unit testing. 
Should I do it? Is it helpful? Is someone else is working on this? 
2. load function is a bit weird.
On the model there are 2 "inputs". One is the image and the other image_shape. 
following the resnet example, I did this: 
`yolo = ONNX.load(path, img, img)`
Did I get it right? I think the interface should be more explicit (or better documentation).
4. Now I got this message: 
```
 Error: Error while loading node ("convolution_output12",) = Conv("input_1", "conv2d_1/kernel:0")
│     dilations => [1, 1]
│     group => 1
│     auto_pad => 
│     kernel_shape => [3, 3]
│     strides => [1, 1]
└ @ ONNX ~/workspace/ONNX.jl/src/load.jl:66
ERROR: auto_pad attribute is currently not supported
```
My plan is to follow the contribution guide to add those features (util I would be able to load the model). 
Is there a list of all the feature that we support, and an if someone is working on a specific one?
5. Is someone worked on this model before and have some insights?

**Comment by ToucheSir** [comment]
> 1. Should I do it? Is it helpful? Is someone else is working on this?

Yes please! I don't believe anyone is working on this, given we have no open code PRs.


> 2\. Did I get it right? I think the interface should be more explicit (or better documentation).

Yes. The [docstring](https://github.com/FluxML/ONNX.jl/blob/master/src/load.jl#L246-L257) looks pretty explicit to me, but we are lacking a proper docs site. Contributions towards that front or documentation in general would be much appreciated.


> Is there a list of all the feature that we support, and an if someone is working on a specific one?

Not really. https://github.com/FluxML/ONNX.jl/blob/master/src/ops.jl has most of them but is not an exhaustive list. To my knowledge, nobody is working on any specific ops right now.

Now to the bigger picture questions:

> First question, is this project alive?

Yes, though development is sporadic because everyone (really dfdx) has day jobs and this library isn't the highest priority in the FluxML org (in part because of user count, see below).


> I mean, I know it is under a big rewrite and the question is whether the community still needs this project? Is the rewrite failed in some way (Flux in compatibility)? etc...

In some sense the rewrite is ready now. We went from a non-functional package which kinda-sorta supported some Flux models to one which should support a wider range of them.

The big missing piece is reading ONNX graphs back in as Flux models. Limiting factors there are time, not wanting to take on Flux as a dependency and mismatch between Flux layers and ONNX operations. Those could be addressed by more external contributions, Julia 1.9 package extensions and an opt-in API with good validation respectively. If this is the most important feature for you, maybe check out https://github.com/DrChainsaw/ONNXNaiveNASflux.jl which is more mature and understands Flux models/

**Comment by dfdx** [comment]
> Did I get it right? I think the interface should be more explicit (or better documentation).

`ONNX.load()` expects the same inputs as you'd use to invoke the model. For example, if the model takes 2 matrices of size `(3, 4)` and `(4, 3)`, then the valid call would be:

```julia
ONNX.load(path, rand(3, 4), rand(4, 3))
```
The reason we need these inputs is to get actual shapes of the tensors flowing through the model, because ONNX itself may not provide information on input shapes. It's more or less common practice, e.g. PyTorch's ONNX exporter requires dummy inputs to collect computation graph, JAX transformations are only materialized when they get input data, etc. 

From your description I understand the inputs must be: 

```julia
ONNX.load(path, img, size(img))
``` 
or 
```julia
ONNX.load(path, img, reverse(size(img)))
```
we may need `reverse` because Julia uses the opposite order of dimensions than Python/ONNX. 
Note that I've never tried to pass non-array inputs to `ONNX.load()`, so if you encounter errors, please post them and tag me to see!

> Now I got this message:

As far as I remember, I saw the `auto_pad` attribute in the [ONNX operator reference](https://github.com/onnx/onnx/blob/main/docs/Operators.md#attributes-16), but didn't have actual ONNX files with it test it. If you are brave enough to dive into it, rememeber that Flux/NNlib only have plain `pads` keyword argument, and that dimensions are again reversed. 

For the rest of the questions, Brian summarized it pretty well.

**Comment by ordicker** [comment]
Hi @ToucheSir and @dfdx 

Thanks for the answers, I will try to send some PR on the simple stuff that I stumble upon.

Regarding ONNX.jl in general. My goal is to use Julia and collaborate with Python user or deep learning project (day job...) and I thought that ONNX format could (and should) be the interface. 
As I see it, a fully functional ONNX package should do the trick. Do you think that could work? 

Thanks again for the help

**Comment by ToucheSir** [comment]
I think the question is what degree of interop you're expecting between Julia and Python. ONNX is an inherently lossy format if you're converting from a higher-level library like Flux, PyTorch or TF, because it removes all notion of "layers" and functions which may be composed of multiple operations. This makes importing ONNX graphs quite difficult. To this day, PyTorch [doesn't support it](https://github.com/pytorch/pytorch/issues/21683)! If you're not worried about the underlying structure of an imported model, ONNX.jl and related libraries are a decent option.

**Comment by ordicker** [comment]
I didn't know that ONNX is a lossy format :( 
Just checking that I got it right, I can't load ONNX (generated by pytorch) file and prune (change layers, etc)  it with Julia? 
The ONNX->pytorch convertion has some project that looks fine(example) , why did you say that PyTorch doesn't support it? Because it's not on the main repo? Why is that?

**Comment by darsnack** [comment]
The library you linked converts base ONNX ops to corresponding operations in PyTorch. This is the same thing that ONNX.jl currently does and aims to do.

But complex "layers" like a inception module in InceptionNet will be broken down into a graph of the base ONNX ops. The grouping of these ops into a more abstract layer is destroyed. This is what makes ONNX inherently lossy. Detecting these subgraphs and matching them to complex layers is hard, and this is the piece that neither PyTorch nor ONNX.jl attempts.

What this means for you is that you can get running models between you and your colleague. But if you want the custom layer classes in PyTorch to map to corresponding Flux.jl layers, then that isn't something we've tackled yet. It would be a non-trivial amount of effort to implement.

**Comment by ordicker** [comment]
Thanks for the explanation. Mapping layers from PyTorch (for example) to Flux would be great, but that's going to be a really hard work. 
In the meantime, I mostly need to convert my models into onnx files to have them accelerate for specific hardware or using them in bigger projects. 
I feel like I'm forced to work with pytorch just because the onnx is incomplete. 

I will try to support this package and hopefully that would help my moving to Julia on my day job.

**Comment by ToucheSir** [comment]
Note that exporting _to_ ONNX is more robust and also easier than importing _from_ ONNX. I'd imagine that's why PyTorch only supports exporting in its main repo. If you can get away with doing everything in [ML library of choice] and only exporting to ONNX once at the end, this is relatively well-supported.

BTW, if you're really interested in pruning models loaded from ONNX files I'd just re-iterate my recommendation to check out https://github.com/DrChainsaw/ONNXNaiveNASflux.jl. Part of the reason ONNX.jl exists as a separate package is because it doesn't need all the pruning and NAS functionality that package provides. But if you do, then it's a one-stop shop :)

**Comment by ordicker** [comment]
Nice package! 
Can we somehow merge it with ONNX.jl? Or at least ONNXNaiveNASflux.jl will use the ONNX.jl read/write functions? 
The resources are limited (Julia developers that use ONNX format) and I think we should try to share code as much as possible (preferably converge to one package).

**Comment by ToucheSir** [comment]
It might be possible. The main question is whether it'd make sense to merge the (very different) graph representations each library uses.
